apiVersion: v1
kind: Service
metadata:
  name: wiki
spec:
  type: LoadBalancer
  selector:
    app: wiki
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 3000 
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki
  labels:
    app: wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
      - name: wiki
        image: requarks/wiki:2
        env:
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: wiki
        - name: DB_NAME
          value: wiki
        - name: DB_PASS
          value: "wiki"
        ports:
        - containerPort: 3000
          name: wiki
          protocol: TCP
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       key: DB_HOST
        #       name: wikijs-config
        # - name: DB_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       key: DB_PORT
        #       name: wikijs-config
        # - name: DB_USER
        #   valueFrom:
        #     configMapKeyRef:
        #       key: DB_USER
        #       name: wikijs-config
        # - name: DB_TYPE
        #   valueFrom:
        #     configMapKeyRef:
        #       key: DB_TYPE
        #       name: wikijs-config
        # - name: DB_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       key: DB_NAME
        #       name: wikijs-config
        # - name: DB_PASS
        #   valueFrom:
        #     configMapKeyRef:
        #       key: DB_PASS
        #       name: wikijs-config
        # - name: DB_PASS
        #   valueFrom:
        #     secretKeyRef:
        #       name: postgres
        #       key: password
      # topologySpreadConstraints:
      # - maxSkew: 1
      #   topologyKey: kubernetes.io/hostname
      #   whenUnsatisfiable: DoNotSchedule
      #   labelSelector:
      #     matchLabels:
      #       app: swap