- name: Postgres Config File
  #become_user: kube
  become: no
  shell: kubectl apply -f ansible/postgres_files/postgres-config.yaml 

- name: Postgres PV File
  #become_user: kube
  become: no
  shell: kubectl apply -f ansible/postgres_files/postgres-pv.yaml 

- name: Postgres Deployment
  #become_user: kube
  become: no
  shell: kubectl apply -f ansible/postgres_files/postgres-deployment.yaml 
