
# - name: Create containerd config file
#   file:
#     path: "/etc/modules-load.d/containerd.conf"
#     state: "touch"

# - name: Add conf for containerd
#   blockinfile:
#     path: "/etc/modules-load.d/containerd.conf"
#     block: |
#           overlay
#           br_netfilter

# - name: modprobe
#   shell: |
#           modprobe overlay
#           modprobe br_netfilter

# - name: Set system configurations for Kubernetes networking
#   file:
#     path: "/etc/sysctl.d/99-kubernetes-cri.conf"
#     state: "touch"

#- name: Add conf for containerd
#  blockinfile:
#   path: "/etc/sysctl.d/99-kubernetes-cri.conf"
#    block: |
#          net.bridge.bridge-nf-call-iptables = 1
#          net.ipv4.ip_forward = 1
#          net.bridge.bridge-nf-call-ip6tables = 1

#- name: Apply new settings
#  command: sysctl --system

#- name: install containerd
#  shell: |
#          apt-get update && apt-get install -y containerd
#          mkdir -p /etc/containerd
#          containerd config default | tee /etc/containerd/config.toml
#          systemctl restart containerd

- name: install and configure dependencies
  shell: |
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

- name: Create kubernetes repo file
  file:
    path: "/etc/apt/sources.list.d/kubernetes.list"
    state: "touch"

- name: Add K8s Source
  blockinfile:
    path: "/etc/apt/sources.list.d/kubernetes.list"
    block: |
          deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: install kubernetes
  shell: |
          apt-get update
          apt-get install -y kubelet kubeadm kubectl
          apt-mark hold kubelet kubeadm kubectl

- name: disable swap
  shell: |
          swapoff -a
          sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: make sure that kubelet service was started and enabled
  service:
    name: kubelet
    state: started
    enabled: yes
