# Tasks common
- name: update system packages
  apt:
    update_cache: yes
    upgrade: no

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: make sure OpenNTPD and OpenSSH services are enabled and running
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ services }}"

- name: install docker
  import_tasks: install_docker.yml

- name: instal kubernetes
  import_tasks: install_kubernetes.yml
