# - name: WikiJs Config File
#   become_user: kube
#   shell: kubectl apply -f $HOME/ansible/wikijsFiles/wikijs-config.yaml 
#   args:
#     chdir: $HOME

- name: WikiJs Secret File
  become_user: kube
  shell: kubectl apply -f $HOME/ansible/wikijsFiles/wikijs-secret.yaml 
  args:
    chdir: $HOME
  
- name: WikiJs Deployment
  become_user: kube
  shell: kubectl apply -f $HOME/ansible/wikijsFiles/wikijs-deployment.yaml 
  args:
    chdir: $HOME