- name: install java
  become: yes
  apt:
    name: openjdk-13-jre-headless
    state: latest
  
- name: Download elasticsearch
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.2-linux-x86_64.tar.gz
    dest: ~/

- name: Unzip elasticsearch Folder
  ansible.builtin.unarchive:
    src: ~/elasticsearch-7.16.2-linux-x86_64.tar.gz
    dest: ~/

- name: Change network.host @ config/elastisearch.yml
  ansible.builtin.replace:
    path: ~/elasticsearch-7.16.2/config/elasticsearch.yml
    regexp: "#network.host:.*\n"
    replace : 'network.host: {{ app_master_ip }}\n'

- name: Change discovery.seed_hosts @ config/elastisearch.yml
  ansible.builtin.replace:
    path: ~/elasticsearch-7.16.2/config/elasticsearch.yml
    regexp: "#discovery.seed_hosts:.*\n"
    replace: "discovery.seed_hosts: []\n"

- name: Change cluster.initial_master_nodes @ config/elastisearch.yml
  ansible.builtin.replace:
    path: ~/elasticsearch-7.16.2/config/elasticsearch.yml
    regexp: "#cluster.initial_master_nodes:.*\n"
    replace: 'cluster.initial_master_nodes: ["{{ app_master_ip }}"]\n'

# - name: start elasticsearch
#   shell: ./elasticsearch-7.16.2/bin/elasticsearch

# - name: Add or modify memlock, both soft and hard, limit for elasticsearch user.
#   pam_limits:
#     domain: elasticsearch
#     limit_type: '-'
#     limit_item: memlock
#     value: unlimited
#     comment: unlimited memory lock for elasticsearch
    
# - name: set LimitMEMLOCK to infinity.
#   lineinfile:
#     path: /usr/lib/systemd/system/elasticsearch.service
#     insertafter: 'LimitAS=infinity'
#     line: 'LimitMEMLOCK=infinity'
#     state: present
    
# - name: set vm.max_map_count to 262144 in sysctl
#   sysctl: name={{ item.key }} value={{ item.value }}
#   with_items:
#     - { key: "vm.max_map_count", value: "262144" }
    
# - name: For a permanent setting, update vm.max_map_count in /etc/sysctl.conf
#   command: sysctl -p /etc/sysctl.conf

# - name: restart elasticsearch after change configuration by configure-elastic-file role
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: elasticsearch
    
# - name: ensure elasticsearch is running
#   systemd:
#     state=started
#     name=elasticsearch