
- name: kubeadm reset
  shell: kubeadm reset --force

- name: kubeadm init
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ app_master_ip }}
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  file:
    path: "{{ kube_dir }}/.kube"
    state: directory
    mode: 0755

- name: copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kube_dir }}/.kube/config"
    remote_src: yes
    owner: kube

# - name: permission
#   shell: chown kube:kube "{{ kube_dir }}/.kube/config"


- name: install Pod network
  become_user: kube
  shell: sudo kubectl apply -f "{{ kube_dir }}/ansible/kube-flannel.yaml"
  args:
    chdir: "{{ kube_dir }}"

- name: Create WikiJs Namespace
  shell: kubectl create namespace wikijs

- name: Get the token for joining the worker nodes
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

# - debug:
#   msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
