
- name: kubeadm reset
  shell: kubeadm reset --force

- name: cleanup before adm init
  shell: |
          systemctl stop kubelet
          systemctl stop docker
          rm -rf /var/lib/cni/
          rm -rf /var/lib/kubelet/*
          rm -rf /etc/cni/
          ifconfig cni0 down
          ifconfig flannel.1 down
          ifconfig docker0 down
          ip link set cni0 down
          brctl delbr cni0
          systemctl restart kubelet
          systemctl restart docker

- name: kubeadm init
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ app_master_ip }}
  args:
    chdir: $HOME
    creates: cluster_initialized.txt

- name: create .kube directory
  #become: yes
  #become_user : kube
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copies admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    #owner: kube

- name: permission
  shell: chown $(id -u):$(id -g) $HOME/.kube/config
  args:
    chdir: $HOME

- name: install Pod network
  #become: yes
  #become_user: kube
  shell: kubectl apply -f $HOME/ansible/kube-flannel.yaml
  args:
    chdir: $HOME #"{{ kube_dir }}"

# - name: Create WikiJs Namespace
  #become: yes
  #become_user: kube
  # shell: kubectl create namespace wikijs
  

- name: Get the token for joining the worker nodes
  #become: yes
  #become_user: kube
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

# - debug:
#   msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
