- hosts: all
  become: yes
  roles:
    - role: common

- hosts: master
  become: yes
  roles:
  - role: master

- hosts: workers
  become: yes
  roles:
  - role: worker

- hosts: master
  become: yes
  roles:
  - role: db

- hosts: master
  become: yes
  roles:
  - role: app
