- name: Reseting kubelet
  shell: kubeadm reset --force

- name: cleanup before adm init
  shell: |
          systemctl stop kubelet
          systemctl stop docker
          rm -rf /var/lib/cni/
          rm -rf /var/lib/kubelet/*
          rm -rf /etc/cni/
          ifconfig cni0 down
          ifconfig flannel.1 down
          ifconfig docker0 down
          ip link set cni0 down
          brctl delbr cni0
          systemctl restart kubelet
          systemctl restart docker

- name: Copy join command from Ansible host to the worker nodes.
  copy:
    src: /tmp/kubernetes_join_command
    dest: /tmp/kubernetes_join_command
    mode: 0777

- name: Join the Worker nodes to the cluster.
  command: sh /tmp/kubernetes_join_command
  register: joined_or_not